apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --volumes hostPath
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: chrome
  name: chrome
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: chrome
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --volumes hostPath
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: chrome
    spec:
      containers:
        - image: selenium/standalone-chrome:latest
          name: chrome
          ports:
            - containerPort: 4444
          resources: {}
      restartPolicy: Always
status: {}
