apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --volumes hostPath
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: mongo
  name: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mongo
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --volumes hostPath
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: mongo
    spec:
      containers:
        - env:
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: bxWd39FJ23A4rMnKDXjm
            - name: MONGO_INITDB_ROOT_USERNAME
              value: root
          image: mongo
          name: mongo
          ports:
            - containerPort: 27017
          resources: {}
          volumeMounts:
            - mountPath: /data/configdb
              name: mongo-hostpath0
            - mountPath: /data/db
              name: mongo-hostpath1
      restartPolicy: Always
      volumes:
        - hostPath:
            path: /home/amar/Projects/writehat/mongo/configdb
          name: mongo-hostpath0
        - hostPath:
            path: /home/amar/Projects/writehat/mongo/db
          name: mongo-hostpath1
status: {}
