# Generated by Django 3.1.7 on 2021-03-25 17:45

from django.db import migrations, models
import django.db.models.deletion
import uuid
import writehat.lib.engagementFinding
import writehat.lib.finding
import writehat.models
import writehat.validation


class Migration(migrations.Migration):

    dependencies = [
        ('writehat', '0002_auto_20201120_1602'),
    ]

    operations = [
        migrations.CreateModel(
            name='ASVSFinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default=str, max_length=1000, validators=[writehat.validation.isValidName])),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('modifiedDate', models.DateTimeField(auto_now=True)),
                ('categoryID', models.UUIDField(editable=False, null=True)),
                ('isApproved', models.BooleanField(blank=True, default=False, null=True)),
                ('background', writehat.models.MarkdownField(blank=True, max_length=30000, null=True)),
                ('remediation', writehat.models.MarkdownField(blank=True, max_length=30000, null=True)),
                ('references', writehat.models.MarkdownField(blank=True, max_length=30000, null=True)),
                ('scoringType', models.CharField(default='ASVS', editable=False, max_length=50)),
                ('vector', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ASVSFindingGroup',
            fields=[
                ('basefindinggroup_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='writehat.basefindinggroup')),
                ('scoringType', models.CharField(default='ASVS', editable=False, max_length=50)),
                ('prefix', models.CharField(default='A', max_length=50, verbose_name='Finding Prefix')),
            ],
            options={
                'abstract': False,
            },
            bases=('writehat.basefindinggroup',),
        ),
        migrations.CreateModel(
            name='ASVSDatabaseFinding',
            fields=[
                ('asvsfinding_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='writehat.asvsfinding')),
            ],
            options={
                'abstract': False,
            },
            bases=(writehat.lib.finding.DatabaseOnlyFinding, 'writehat.asvsfinding'),
        ),
        migrations.CreateModel(
            name='ASVSEngagementFinding',
            fields=[
                ('asvsfinding_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='writehat.asvsfinding')),
                ('findingGroup', models.UUIDField(editable=False, null=True)),
                ('asvsStatus', models.CharField(blank=True, max_length=10, null=True)),
                ('asvsSeverity', models.CharField(blank=True, max_length=10, null=True)),
                ('asvsRecommendation', writehat.models.MarkdownField(blank=True, max_length=30000, null=True)),
                ('asvsReferences', writehat.models.MarkdownField(blank=True, max_length=30000, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(writehat.lib.engagementFinding.EngagementFinding, 'writehat.asvsfinding'),
        ),
    ]
