# Generated by Django 3.1.7 on 2021-03-25 18:25

from django.db import migrations, models
import writehat.models


class Migration(migrations.Migration):

    dependencies = [
        ('writehat', '0003_asvsdatabasefinding_asvsengagementfinding_asvsfinding_asvsfindinggroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asvsfinding',
            name='vector',
        ),
        migrations.AddField(
            model_name='asvsfinding',
            name='asvsDescription',
            field=writehat.models.MarkdownField(blank=True, max_length=30000, null=True),
        ),
        migrations.AddField(
            model_name='asvsfinding',
            name='asvsDocumentation',
            field=writehat.models.MarkdownField(blank=True, max_length=30000, null=True),
        ),
        migrations.AddField(
            model_name='asvsfinding',
            name='asvsEvidence',
            field=writehat.models.MarkdownField(blank=True, max_length=30000, null=True),
        ),
        migrations.AddField(
            model_name='asvsfinding',
            name='asvsNumber',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='asvsfinding',
            name='asvsTools',
            field=writehat.models.MarkdownField(blank=True, max_length=30000, null=True),
        ),
    ]
